# -*- coding: utf-8 -*-
"""Atividade PLN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJNWrAyu8YcEMQ_gAW2He-FpfIJJLEeC
"""

import nltk
nltk.download('stopwords')
nltk.download('webtext')
from nltk.corpus import stopwords
from nltk.corpus import webtext

path='pirates.txt'
wordsFromPath=webtext.words(path)
tokens=nltk.FreqDist(wordsFromPath)
stopwords=set(stopwords.words('english'))
withoutStopWord=[word for word in webtext.words(path) if word not in stopwords]

print('\nTokens distintos:')
print(tokens.N())
print('\nOs 10 tokens mais comuns:')
print(tokens.most_common(10))
print('\nTexto limpo, sem as stopwords:')
print(withoutStopWord)